#!/usr/bin/env bash

addon=$1
out=$1.ankiaddon

if [ -a $addon/__init__.py ]
then
    echo - packaging $addon
    rm -f $out
	rm -f $addon/meta.json
	rm -rf $addon/__pycache__
	cd $addon/
    zip -r ../$out *
fi
