#!/usr/bin/env bash

addon=$1
out=$1.ankiaddon

if [ -a $addon/__init__.py ]
then
    echo - packaging $addon
    rm -f $out
	rm -rf $addon/__pycache__
	cd $addon/
    echo "{\"package\": \"$addon\", \"name\": \"$addon\"}" > manifest.json
    zip -r ../$out *
fi
